[package]
name = "snail-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
snail-core = { path = "../crates/snail-core" }

[[bin]]
name = "pgp_parse"
path = "fuzz_targets/pgp_parse.rs"
test = false
doc = false
bench = false
